; Listing generated by Microsoft (R) Optimizing Compiler Version 19.38.33145.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__64E34937_EndBrace@h DB 01H
msvcjmc	ENDS
END
