; Listing generated by Microsoft (R) Optimizing Compiler Version 19.38.33145.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__33BC6ACF_math@cpp DB 01H
msvcjmc	ENDS
END
